/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace SeenovarSettlementRegistry {
      
    export type SettlementRecordStruct = {settlementIdHash: BytesLike, transactionHash: BytesLike, chainId: BigNumberish, amountMinorUnits: BigNumberish, asset: AddressLike, senderWallet: AddressLike, recipientWallet: AddressLike, status: BigNumberish, registeredAt: BigNumberish, reconciledAt: BigNumberish}

    export type SettlementRecordStructOutput = [settlementIdHash: string, transactionHash: string, chainId: bigint, amountMinorUnits: bigint, asset: string, senderWallet: string, recipientWallet: string, status: bigint, registeredAt: bigint, reconciledAt: bigint] & {settlementIdHash: string, transactionHash: string, chainId: bigint, amountMinorUnits: bigint, asset: string, senderWallet: string, recipientWallet: string, status: bigint, registeredAt: bigint, reconciledAt: bigint }
  
    }

  export interface SeenovarSettlementRegistryInterface extends Interface {
    getFunction(nameOrSignature: "exists" | "getSettlement" | "isReconciled" | "markReconciled" | "owner" | "registerSettlement"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "SettlementReconciled" | "SettlementRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'exists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSettlement', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isReconciled', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'markReconciled', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerSettlement', values: [BytesLike, BytesLike, BigNumberish, BigNumberish, AddressLike, AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSettlement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isReconciled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markReconciled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerSettlement', data: BytesLike): Result;
  }

  
    export namespace SettlementReconciledEvent {
      export type InputTuple = [settlementIdHash: BytesLike, reconciledAt: BigNumberish];
      export type OutputTuple = [settlementIdHash: string, reconciledAt: bigint];
      export interface OutputObject {settlementIdHash: string, reconciledAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettlementRegisteredEvent {
      export type InputTuple = [settlementIdHash: BytesLike, transactionHash: BytesLike, chainId: BigNumberish, asset: AddressLike, senderWallet: AddressLike, recipientWallet: AddressLike, amountMinorUnits: BigNumberish];
      export type OutputTuple = [settlementIdHash: string, transactionHash: string, chainId: bigint, asset: string, senderWallet: string, recipientWallet: string, amountMinorUnits: bigint];
      export interface OutputObject {settlementIdHash: string, transactionHash: string, chainId: bigint, asset: string, senderWallet: string, recipientWallet: string, amountMinorUnits: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SeenovarSettlementRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): SeenovarSettlementRegistry;
    waitForDeployment(): Promise<this>;

    interface: SeenovarSettlementRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    exists: TypedContractMethod<
      [settlementIdHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getSettlement: TypedContractMethod<
      [settlementIdHash: BytesLike, ],
      [SeenovarSettlementRegistry.SettlementRecordStructOutput],
      'view'
    >
    

    
    isReconciled: TypedContractMethod<
      [settlementIdHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    markReconciled: TypedContractMethod<
      [settlementIdHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerSettlement: TypedContractMethod<
      [settlementIdHash: BytesLike, transactionHash: BytesLike, chainId: BigNumberish, amountMinorUnits: BigNumberish, asset: AddressLike, senderWallet: AddressLike, recipientWallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'exists'): TypedContractMethod<
      [settlementIdHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getSettlement'): TypedContractMethod<
      [settlementIdHash: BytesLike, ],
      [SeenovarSettlementRegistry.SettlementRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isReconciled'): TypedContractMethod<
      [settlementIdHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'markReconciled'): TypedContractMethod<
      [settlementIdHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerSettlement'): TypedContractMethod<
      [settlementIdHash: BytesLike, transactionHash: BytesLike, chainId: BigNumberish, amountMinorUnits: BigNumberish, asset: AddressLike, senderWallet: AddressLike, recipientWallet: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'SettlementReconciled'): TypedContractEvent<SettlementReconciledEvent.InputTuple, SettlementReconciledEvent.OutputTuple, SettlementReconciledEvent.OutputObject>;
getEvent(key: 'SettlementRegistered'): TypedContractEvent<SettlementRegisteredEvent.InputTuple, SettlementRegisteredEvent.OutputTuple, SettlementRegisteredEvent.OutputObject>;

    filters: {
      
      'SettlementReconciled(bytes32,uint256)': TypedContractEvent<SettlementReconciledEvent.InputTuple, SettlementReconciledEvent.OutputTuple, SettlementReconciledEvent.OutputObject>;
      SettlementReconciled: TypedContractEvent<SettlementReconciledEvent.InputTuple, SettlementReconciledEvent.OutputTuple, SettlementReconciledEvent.OutputObject>;
    

      'SettlementRegistered(bytes32,bytes32,uint256,address,address,address,uint256)': TypedContractEvent<SettlementRegisteredEvent.InputTuple, SettlementRegisteredEvent.OutputTuple, SettlementRegisteredEvent.OutputObject>;
      SettlementRegistered: TypedContractEvent<SettlementRegisteredEvent.InputTuple, SettlementRegisteredEvent.OutputTuple, SettlementRegisteredEvent.OutputObject>;
    
    };
  }